#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6504303742                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : lb                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/lb/app/ganttlify/id6504303742                                         # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.ideer                                          # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : ganttLify                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Launch date: 2 August, currently available as pre order on Apple app store & available for beta testers on google play store(Full availability on 2 August).
                                             Transform project management with our gamified app! Track, analyze, and visualize your tasks effortlessly using Gantt charts, EVM, CPM, curves... For pros and hobbyists!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : innovatony                              
your_link                                 : https://innovatony.com                     
your_city                                 :                                 
email_address                             : antoinenaoun@gmail.com
facebook_username                         :                                           
instagram_username                        : innovatonyy
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Critical Path Method (CPM)
    description                           : Identify the most crucial tasks that can impact your project's timeline. Stay ahead by focusing on these critical activities to ensure timely project completion.
    fontawesome_icon_name                 : chart-bar
    
  - title                                 : Earned Value Management (EVM)
    description                           : Track your project’s performance with precision. Analyze cost and schedule variances to keep your project on budget and on time.
    fontawesome_icon_name                 : file-invoice

  - title                                 : Gantt Chart
    description                           : Visualize your project timeline with Gantt charts. Easily see task dependencies, deadlines, and progress at a glance.
    fontawesome_icon_name                 : chart-bar

  - title                                 : Cumulative Cost Curve (SCurve)
    description                           : Monitor your project’s financial health with cumulative cost curves. Compare planned vs. actual spending to control costs effectively.
    fontawesome_icon_name                 : chart-line

  - title                                 : Text Notes & To-Dos
    description                           : Organize your thoughts and tasks with simple text notes and to-dos. Never miss a detail, whether it's a quick reminder or a comprehensive task list.
    fontawesome_icon_name                 : pen
  
  - title                                 : Sketch & Draw
    description                           : Bring your ideas to life with sketches and drawings. Visualize tasks and concepts in a creative, intuitive way that enhances understanding and communication.
    fontawesome_icon_name                 : chalkboard

  - title                                 : AI support (Soon)
    description                           : Unlock the future of project management with our AI-powered tools, leveraging data-driven insights to enhance efficiency, accuracy, and success in your projects.
    fontawesome_icon_name                 : robot

  - title                                 : AR/VR support (Soon)
    description                           : Experience the next level of project management with immersive AR and VR capabilities, seamlessly integrated for enhanced visualization and collaboration using devices like Apple Vision Pro.
    fontawesome_icon_name                 : vr-cardboard

  - title                                 : Voice note support (Soon)
    description                           : Navigate the app faster with audio / voice note commands!
    fontawesome_icon_name                 : microphone

  - title                                 : Teams support (Soon)
    description                           : Work in teams! Communicate & Leverage the tools here to co-track tasks
    fontawesome_icon_name                 : user-plus



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/feature.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
